# Generated by Django 4.1.4 on 2022-12-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='location',
            field=models.CharField(default='hello', max_length=50),
            preserve_default=False,
        ),
    ]
