# Generated by Django 4.1.4 on 2022-12-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcan', '0003_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='extinct',
            field=models.CharField(default='h', max_length=50),
            preserve_default=False,
        ),
    ]
