# Generated by Django 4.1.4 on 2022-12-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcan', '0002_qrcode_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('confpassword', models.CharField(max_length=255)),
            ],
        ),
    ]
